services:
  - type: web
    name: weather-backend
    env: java
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/*.jar"
    plan: free
    branch: main
    region: oregon
    repo: https://github.com/YashMahajan45/weather-backend
